import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  ArrowUp,
  Bot,
  Box,
  Check,
  Code2,
  Download,
  ExternalLink,
  FileText,
  LayoutDashboard,
  Loader2,
  Monitor,
  Play,
  RefreshCw,
  Rocket,
  Smartphone,
  Terminal,
} from "lucide-react";
import "./styles.css";

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || "http://localhost:7860").replace(/\/$/, "");

const fallbackTemplates = [
  {
    id: "crm",
    name: "AI CRM Sprint",
    slug: "ai-crm-sprint",
    summary: "Pipeline, tasks, analytics, permissions, and follow-up workflows.",
    title: "Sales pipeline that updates itself",
    copy: "智能体已经生成客户列表、销售阶段、提醒任务和转化分析。继续对话即可增删页面或调整数据模型。",
    buttons: ["Create lead", "Review pipeline"],
    cards: [
      { title: "Pipeline", copy: "按阶段管理机会，自动标记高优先级客户。" },
      { title: "Tasks", copy: "从邮件和会议纪要中提取下一步行动。" },
      { title: "Analytics", copy: "追踪赢单率、响应时间和预测收入。" },
    ],
  },
  {
    id: "shop",
    name: "Commerce Launchpad",
    slug: "commerce-launchpad",
    summary: "Catalog, cart, checkout, order operations, and inventory states.",
    title: "Storefront, checkout, and ops in one build",
    copy: "生成商品目录、库存状态、购物车、结账流程和订单后台，适合快速验证电商项目。",
    buttons: ["Add product", "Open orders"],
    cards: [
      { title: "Catalog", copy: "支持分类、标签、变体和库存状态。" },
      { title: "Checkout", copy: "包含地址、优惠码、支付摘要和确认页。" },
      { title: "Orders", copy: "按状态追踪履约、退款和客户沟通。" },
    ],
  },
  {
    id: "learn",
    name: "Learning Studio",
    slug: "learning-studio",
    summary: "Courses, lessons, quizzes, learner progress, and authoring tools.",
    title: "Course platform with progress-aware lessons",
    copy: "生成课程首页、课时播放器、测验、学习进度和教师内容管理工作台。",
    buttons: ["Create course", "Preview lesson"],
    cards: [
      { title: "Courses", copy: "按模块组织视频、阅读材料和附件。" },
      { title: "Quizzes", copy: "自动生成题目、反馈和通过规则。" },
      { title: "Progress", copy: "展示完成率、薄弱知识点和学习提醒。" },
    ],
  },
];

const fallbackProjects = [
];

function buildLocalCode(build) {
  return `// Generated by Atoms Agent Builder Demo
export default function ${build.preview.name.replace(/[^a-zA-Z0-9]/g, "")}() {
  const cards = ${JSON.stringify(build.preview.cards, null, 2)};

  return (
    <AppShell mode="${build.mode}">
      <Hero title="${build.preview.title}" description="${build.preview.copy}" />
      <FeatureGrid cards={cards} />
      <AgentRuntime preview code logs export publish />
    </AppShell>
  );
}`;
}

function initialBuild(template = fallbackTemplates[0]) {
  return {
    id: "local_seed",
    status: "ready",
    mode: "fast",
    templateId: template.id,
    prompt: template.copy,
    createdAt: new Date().toISOString(),
    steps: [
      { id: "planner", agent: "Planner", title: "已初始化项目范围", durationMs: 500 },
      { id: "coder", agent: "Coder", title: "已生成基础预览", durationMs: 500 },
      { id: "verifier", agent: "Verifier", title: "等待下一次构建", durationMs: 500 },
    ],
    message: "你好，我是构建智能体。描述你想做的项目，我会生成页面结构、核心交互、预览和代码片段。",
    preview: {
      name: template.name,
      slug: template.slug,
      title: template.title,
      copy: template.copy,
      buttons: template.buttons,
      cards: template.cards,
      url: `https://preview.atoms.local/${template.slug}`,
    },
    code: "",
    logs: ["[init] frontend mounted", "[preview] waiting for backend or next user request"],
  };
}

async function api(path, options = {}) {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    ...options,
  });
  if (!response.ok) {
    const detail = await response.text();
    throw new Error(detail || `Request failed: ${response.status}`);
  }
  return response.json();
}

function App() {
  const [templates, setTemplates] = useState(fallbackTemplates);
  const [projects, setProjects] = useState(fallbackProjects);
  const [activeTemplateId, setActiveTemplateId] = useState("crm");
  const [activeProjectId, setActiveProjectId] = useState("crm-sprint");
  const [mode, setMode] = useState("fast");
  const [build, setBuild] = useState(() => {
    const seed = initialBuild();
    seed.code = buildLocalCode(seed);
    return seed;
  });
  const [messages, setMessages] = useState([
    { id: "welcome", role: "assistant", text: "你好，我是构建智能体。先告诉我你想做什么网站或应用，我会逐步确认风格、页面内容和核心功能，然后生成预览与代码。" },
  ]);
  const [intake, setIntake] = useState({ phase: "idea", idea: "", style: "", content: "" });
  const [showPreview, setShowPreview] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [tab, setTab] = useState("preview");
  const [mobile, setMobile] = useState(false);
  const [buildState, setBuildState] = useState("Ready");
  const [activeAgentIndex, setActiveAgentIndex] = useState(0);
  const [stepStates, setStepStates] = useState({});
  const [toast, setToast] = useState("");
  const [apiReady, setApiReady] = useState(false);
  const messagesRef = useRef(null);

  const activeTemplate = useMemo(
    () => templates.find((template) => template.id === activeTemplateId) || templates[0],
    [activeTemplateId, templates],
  );

  useEffect(() => {
    Promise.all([api("/api/templates"), api("/api/projects")])
      .then(([templateData, projectData]) => {
        setTemplates(templateData.templates);
        setProjects([]);
        setApiReady(true);
      })
      .catch(() => setApiReady(false));
  }, []);

  useEffect(() => {
    if (messagesRef.current) {
      messagesRef.current.scrollTop = messagesRef.current.scrollHeight;
    }
  }, [messages, stepStates]);

  function notify(text) {
    setToast(text);
    window.setTimeout(() => setToast(""), 2200);
  }

  function animateBuild(nextBuild) {
    setBuildState("Building");
    setActiveAgentIndex(0);
    setStepStates(Object.fromEntries(nextBuild.steps.map((step) => [step.id, "pending"])));

    let elapsed = 120;
    nextBuild.steps.forEach((step, index) => {
      window.setTimeout(() => {
        setActiveAgentIndex(index);
        setStepStates((current) => ({ ...current, [step.id]: "running" }));
      }, elapsed);
      elapsed += step.durationMs;
      window.setTimeout(() => {
        setStepStates((current) => ({ ...current, [step.id]: "done" }));
        if (index === nextBuild.steps.length - 1) {
          setBuildState("Ready");
          setActiveAgentIndex(2);
        }
      }, elapsed);
    });
  }

  async function createBuild(text, templateId = activeTemplateId, appendUserMessage = true) {
    const userText = text.trim();
    if (!userText) return;
    if (appendUserMessage) {
      setMessages((items) => [...items, { id: crypto.randomUUID(), role: "user", text: userText }]);
    }
    setPrompt("");
    setBuildState("Building");

    try {
      const data = await api("/api/builds", {
        method: "POST",
        body: JSON.stringify({
          prompt: userText,
          template_id: templateId,
          mode,
          history: messages.slice(-8).map((message) => ({
            role: message.role === "assistant" ? "assistant" : "user",
            content: message.text,
          })),
        }),
      });
      const nextBuild = data.build;
      setBuild(nextBuild);
      setActiveTemplateId(nextBuild.templateId);
      setShowPreview(true);
      animateBuild(nextBuild);
      const project = {
        id: nextBuild.id,
        name: nextBuild.preview.name || "Generated Project",
        templateId: nextBuild.templateId,
        updated: "Now",
      };
      setProjects((items) => [project, ...items.filter((item) => item.id !== project.id)]);
      setActiveProjectId(project.id);
      setMessages((items) => [
        ...items,
        {
          id: nextBuild.id,
          role: "assistant",
          text: nextBuild.message,
          steps: nextBuild.steps,
        },
      ]);
    } catch (error) {
      setBuildState("Offline");
      setMessages((items) => [
        ...items,
        { id: crypto.randomUUID(), role: "assistant", text: `后端暂时不可用：${error.message}` },
      ]);
    }
  }

  function handleGuidedSubmit(text) {
    const userText = text.trim();
    if (!userText) return;

    setMessages((items) => [...items, { id: crypto.randomUUID(), role: "user", text: userText }]);
    setPrompt("");

    if (intake.phase === "idea") {
      setIntake({ phase: "style", idea: userText, style: "", content: "" });
      setMessages((items) => [
        ...items,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          text: "好的。你希望这个项目是什么视觉风格？例如：极简专业、深色科技感、活泼插画风、企业级后台、移动端优先，或者你可以描述参考网站。",
        },
      ]);
      return;
    }

    if (intake.phase === "style") {
      setIntake((current) => ({ ...current, phase: "content", style: userText }));
      setMessages((items) => [
        ...items,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          text: "收到。接下来请告诉我需要哪些页面和内容模块，比如首页、价格页、登录页、仪表盘、表单、列表、图表、文案重点或数据字段。",
        },
      ]);
      return;
    }

    if (intake.phase === "content") {
      const fullPrompt = [
        `项目目标：${intake.idea}`,
        `视觉风格：${intake.style}`,
        `页面与内容：${userText}`,
        "请生成适合前端展示的 preview、React 代码、构建日志，并体现 Planner、Coder、Verifier 的构建过程。",
      ].join("\n");
      setIntake((current) => ({ ...current, phase: "done", content: userText }));
      createBuild(fullPrompt, activeTemplateId, false);
      return;
    }

    createBuild(userText);
  }

  async function rerun() {
    if (!apiReady || build.id === "local_seed") {
      createBuild(`重新运行 ${activeTemplate.name}，保持当前功能但优化视觉层级。`, activeTemplateId);
      return;
    }
    setBuildState("Building");
    try {
      const data = await api("/api/builds/rerun", {
        method: "POST",
        body: JSON.stringify({ build_id: build.id, mode }),
      });
      setBuild(data.build);
      animateBuild(data.build);
      setMessages((items) => [
        ...items,
        { id: crypto.randomUUID(), role: "user", text: "重新运行当前构建。" },
        { id: data.build.id, role: "assistant", text: data.build.message, steps: data.build.steps },
      ]);
    } catch (error) {
      setBuildState("Offline");
      notify("Rerun failed");
    }
  }

  async function publish() {
    if (!apiReady || build.id === "local_seed") {
      setBuildState("Published");
      notify("Published locally");
      return;
    }
    try {
      const data = await api("/api/publish", {
        method: "POST",
        body: JSON.stringify({ build_id: build.id }),
      });
      setBuildState("Published");
      setBuild((current) => ({
        ...current,
        logs: [...current.logs, `[publish] ${data.publish.url}`],
      }));
      notify("Published to preview URL");
    } catch (error) {
      notify("Publish failed");
    }
  }

  function exportBuild() {
    if (apiReady && build.id !== "local_seed") {
      window.location.href = `${API_BASE_URL}/api/builds/${build.id}/export`;
      notify("Preparing export artifact");
      return;
    }
    const blob = new Blob([JSON.stringify(build, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${build.preview.slug}.json`;
    link.click();
    URL.revokeObjectURL(url);
  }

  function selectTemplate(templateId) {
    const template = templates.find((item) => item.id === templateId);
    if (!template) return;
    setActiveTemplateId(templateId);
    const nextBuild = initialBuild(template);
    nextBuild.code = buildLocalCode(nextBuild);
    setBuild(nextBuild);
    setBuildState("Ready");
    notify("Starter kit loaded");
  }

  function selectProject(project) {
    setActiveProjectId(project.id);
    selectTemplate(project.templateId);
  }

  const aiLog = build.ai
    ? `[ai-status] enabled=${build.ai.enabled} used=${build.ai.used} model=${build.ai.model || "none"}${build.ai.lastError ? ` error=${build.ai.lastError}` : ""}`
    : "[ai-status] unknown";
  const logText = [aiLog, ...(build.logs || [])].join("\n");

  return (
    <main className={`app-shell ${showPreview ? "with-preview" : "builder-only"}`}>
      <aside className="sidebar" aria-label="项目导航">
        <div className="brand">
          <div className="logo">
            <span className="mark">A</span>
            <span>Atoms Demo</span>
          </div>
          <span className={apiReady ? "status-pill" : "status-pill muted-pill"}>
            <span className="dot" />
            {apiReady ? "API Live" : "Local"}
          </span>
        </div>

        <section className="side-section">
          <h2 className="section-title">Projects</h2>
          <div className="project-list">
            {projects.length === 0 ? (
              <div className="empty-projects">还没有项目。完成一次构建后会出现在这里。</div>
            ) : projects.map((project) => (
              <button
                key={project.id}
                className={`nav-item ${activeProjectId === project.id ? "active" : ""}`}
                type="button"
                onClick={() => selectProject(project)}
              >
                <span className="nav-name">
                  <span className="icon"><LayoutDashboard size={14} /></span>
                  {project.name}
                </span>
                <span className="tiny">{project.updated}</span>
              </button>
            ))}
          </div>
        </section>
      </aside>

      <section className="chat" aria-label="智能体构建对话">
        <header className="topbar">
          <div className="title-block">
            <h1>Agent Project Builder</h1>
            <p>把需求交给智能体，实时生成可预览的应用。</p>
          </div>
          <div className="segmented" aria-label="构建模式">
            {["fast", "deep"].map((item) => (
              <button key={item} className={mode === item ? "active" : ""} type="button" onClick={() => setMode(item)}>
                {item === "fast" ? "Fast" : "Deep"}
              </button>
            ))}
          </div>
        </header>

        <div className={`agents ${showPreview ? "" : "compact-agents"}`}>
          {["Idea", "Style", "Scope"].map((agent, index) => (
            <div
              key={agent}
              className={`agent ${["idea", "style", "content"][index] === intake.phase ? "running" : ""} ${index < ["idea", "style", "content", "done"].indexOf(intake.phase) ? "done" : ""}`}
            >
              <div className="agent-head">
                <span>{agent}</span>
                <span className="agent-state" />
              </div>
              <p>{index === 0 ? "确认产品目标。" : index === 1 ? "确认视觉方向。" : "确认页面和内容。"}</p>
            </div>
          ))}
        </div>

        <div className="messages" ref={messagesRef}>
          {messages.map((message) => (
            <article key={message.id} className={`message ${message.role}`}>
              <div className="bubble">
                <p>{message.text}</p>
                {message.steps ? (
                  <div className="steps">
                    {message.steps.map((step) => {
                      const state = stepStates[step.id] || "pending";
                      return (
                        <div key={step.id} className={`step ${state}`}>
                          <span className="step-mark">
                            {state === "done" ? <Check size={12} /> : state === "running" ? <Loader2 size={12} className="spin" /> : step.agent.slice(0, 1)}
                          </span>
                          <span>{step.agent} · {step.title}</span>
                        </div>
                      );
                    })}
                  </div>
                ) : null}
              </div>
            </article>
          ))}
        </div>

        <form className="composer" onSubmit={(event) => { event.preventDefault(); handleGuidedSubmit(prompt); }}>
          <div className="input-wrap">
            <textarea
              value={prompt}
              onChange={(event) => setPrompt(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter" && !event.shiftKey) {
                  event.preventDefault();
                  handleGuidedSubmit(prompt);
                }
              }}
              placeholder={intake.phase === "idea" ? "例如：我想做一个帮助学生整理课程笔记的网站。" : intake.phase === "style" ? "例如：极简、专业、偏白色背景，适合大学生使用。" : "例如：首页、登录页、笔记列表、AI 总结页、标签筛选和导出功能。"}
            />
            <button className="send" type="submit" title="发送"><ArrowUp size={20} /></button>
          </div>
          <div className="quick-row" aria-label="快捷需求">
            {(intake.phase === "idea" ? ["SaaS 后台", "作品集网站", "AI 学习工具"] : intake.phase === "style" ? ["极简专业", "深色科技", "清爽教育风"] : ["首页和登录", "Dashboard 和表格", "表单和图表"]).map((item) => (
              <button key={item} className="chip" type="button" onClick={() => setPrompt(item)}>
                {item}
              </button>
            ))}
          </div>
        </form>
      </section>

      {showPreview ? <section className="workspace" aria-label="应用预览工作区">
        <header className="workspace-head">
          <div className="title-block">
            <h1>{build.preview.name}</h1>
            <p>Preview generated from {build.id}</p>
          </div>
          <div className="actions">
            <button className="icon-btn" type="button" onClick={rerun} title="重新运行"><RefreshCw size={17} /></button>
            <button className="icon-btn" type="button" onClick={() => setMobile((value) => !value)} title="切换设备">
              {mobile ? <Monitor size={17} /> : <Smartphone size={17} />}
            </button>
            <button className="text-btn" type="button" onClick={exportBuild}><Download size={14} />Export</button>
            <button className="text-btn primary" type="button" onClick={publish}><Rocket size={14} />Publish</button>
          </div>
        </header>

        <div className="tabs" role="tablist" aria-label="工作区视图">
          {[
            ["preview", "Preview", Play],
            ["code", "Code", Code2],
            ["logs", "Logs", Terminal],
          ].map(([id, label, Icon]) => (
            <button key={id} className={`tab ${tab === id ? "active" : ""}`} type="button" onClick={() => setTab(id)}>
              <Icon size={14} />{label}
            </button>
          ))}
        </div>

        <div className="workspace-body">
          <div className="viewport-bar">
            <div className="address"><ExternalLink size={13} />{build.preview.url}</div>
            <span className={`status-pill ${buildState === "Building" ? "blue-pill" : ""}`}>
              <span className="dot" />
              {buildState}
            </span>
          </div>

          {tab === "preview" ? (
            <div className="viewer">
              <PreviewApp build={build} mobile={mobile} />
            </div>
          ) : tab === "code" ? (
            <pre className="code-view">{build.code || buildLocalCode(build)}</pre>
          ) : (
            <pre className="log-view">{logText}</pre>
          )}
        </div>
      </section> : null}

      <div className={`toast ${toast ? "show" : ""}`} role="status" aria-live="polite">{toast}</div>
    </main>
  );
}

function PreviewApp({ build, mobile }) {
  const preview = build.preview || {};
  const nav = preview.nav || [];
  const metrics = preview.metrics || [];
  const sections = preview.sections || [];

  return (
    <div className={`preview-app ${mobile ? "mobile" : ""} theme-${preview.theme || "light"}`}>
      {nav.length ? (
        <nav className="generated-nav">
          <strong>{preview.name || build.preview.name}</strong>
          <div>
            {nav.map((item) => <span key={item}>{item}</span>)}
          </div>
        </nav>
      ) : null}
      <section className="preview-hero">
        <div>
          <h2>{preview.title}</h2>
          <p>{preview.copy}</p>
          <div className="preview-buttons">
            {(preview.buttons || []).map((button, index) => (
              <button key={button} className={`mock-btn ${index > 0 ? "alt" : ""}`} type="button">
                {button}
              </button>
            ))}
          </div>
        </div>
        <div className="visual" aria-hidden="true">
          <div className="visual-line wide" />
          <div className="visual-line warm" />
          <div className="visual-grid">
            <div className="visual-tile" />
            <div className="visual-tile blue" />
            <div className="visual-tile gold" />
          </div>
          <div className="visual-line mid" />
        </div>
      </section>
      {metrics.length ? (
        <section className="metrics-grid">
          {metrics.map((metric) => (
            <div className="metric-card" key={metric.title}>
              <span>{metric.title}</span>
              <b>{metric.copy}</b>
            </div>
          ))}
        </section>
      ) : null}
      <section className="preview-content">
        {(preview.cards || []).map((card) => (
          <div className="preview-card" key={card.title}>
            <b>{card.title}</b>
            <span>{card.copy}</span>
          </div>
        ))}
      </section>
      {sections.length ? (
        <section className="generated-sections">
          {sections.map((section) => (
            <article className="generated-section" key={section.title}>
              <h3>{section.title}</h3>
              <p>{section.copy}</p>
              {section.bullets?.length ? (
                <ul>
                  {section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}
                </ul>
              ) : null}
            </article>
          ))}
        </section>
      ) : null}
      <section className="preview-strip">
        <div><Bot size={16} />Agent generated</div>
        <div><Box size={16} />Componentized</div>
        <div><FileText size={16} />Exportable</div>
      </section>
    </div>
  );
}

createRoot(document.getElementById("root")).render(<App />);
