from __future__ import annotations

import io
import json
import os
import time
import uuid
import zipfile
from datetime import datetime, timezone
from typing import Literal

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field


TemplateId = Literal["crm", "shop", "learn"]
BuildMode = Literal["fast", "deep"]


class BuildRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=1200)
    template_id: TemplateId = "crm"
    mode: BuildMode = "fast"


class RerunRequest(BaseModel):
    build_id: str
    instruction: str | None = None
    mode: BuildMode = "fast"


class PublishRequest(BaseModel):
    build_id: str


TEMPLATES = {
    "crm": {
        "id": "crm",
        "name": "AI CRM Sprint",
        "slug": "ai-crm-sprint",
        "summary": "Pipeline, tasks, analytics, permissions, and follow-up workflows.",
        "title": "Sales pipeline that updates itself",
        "copy": "智能体已经生成客户列表、销售阶段、提醒任务和转化分析。继续对话即可增删页面或调整数据模型。",
        "buttons": ["Create lead", "Review pipeline"],
        "cards": [
            {"title": "Pipeline", "copy": "按阶段管理机会，自动标记高优先级客户。"},
            {"title": "Tasks", "copy": "从邮件和会议纪要中提取下一步行动。"},
            {"title": "Analytics", "copy": "追踪赢单率、响应时间和预测收入。"},
        ],
    },
    "shop": {
        "id": "shop",
        "name": "Commerce Launchpad",
        "slug": "commerce-launchpad",
        "summary": "Catalog, cart, checkout, order operations, and inventory states.",
        "title": "Storefront, checkout, and ops in one build",
        "copy": "生成商品目录、库存状态、购物车、结账流程和订单后台，适合快速验证电商项目。",
        "buttons": ["Add product", "Open orders"],
        "cards": [
            {"title": "Catalog", "copy": "支持分类、标签、变体和库存状态。"},
            {"title": "Checkout", "copy": "包含地址、优惠码、支付摘要和确认页。"},
            {"title": "Orders", "copy": "按状态追踪履约、退款和客户沟通。"},
        ],
    },
    "learn": {
        "id": "learn",
        "name": "Learning Studio",
        "slug": "learning-studio",
        "summary": "Courses, lessons, quizzes, learner progress, and authoring tools.",
        "title": "Course platform with progress-aware lessons",
        "copy": "生成课程首页、课时播放器、测验、学习进度和教师内容管理工作台。",
        "buttons": ["Create course", "Preview lesson"],
        "cards": [
            {"title": "Courses", "copy": "按模块组织视频、阅读材料和附件。"},
            {"title": "Quizzes", "copy": "自动生成题目、反馈和通过规则。"},
            {"title": "Progress", "copy": "展示完成率、薄弱知识点和学习提醒。"},
        ],
    },
}


PROJECTS = [
    {"id": "crm-sprint", "name": "AI CRM Sprint", "templateId": "crm", "updated": "Now"},
    {"id": "finops-board", "name": "FinOps Board", "templateId": "shop", "updated": "2h"},
    {"id": "docs-portal", "name": "Docs Portal", "templateId": "learn", "updated": "1d"},
]


BUILDS: dict[str, dict] = {}
PUBLISHED: dict[str, dict] = {}


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def detect_template(prompt: str, fallback: TemplateId) -> TemplateId:
    text = prompt.lower()
    if any(word in text for word in ["电商", "商品", "订单", "购物", "shop", "commerce", "store"]):
        return "shop"
    if any(word in text for word in ["课程", "学习", "lesson", "course", "education", "quiz"]):
        return "learn"
    if any(word in text for word in ["crm", "销售", "客户", "pipeline", "lead"]):
        return "crm"
    return fallback


def summarize_requirement(prompt: str) -> str:
    prompt = " ".join(prompt.strip().split())
    if len(prompt) <= 92:
        return prompt
    return f"{prompt[:92]}..."


def generated_code(template: dict, prompt: str, mode: BuildMode) -> str:
    component_name = "".join(part for part in template["name"].title() if part.isalnum())
    cards_json = json.dumps(template["cards"], ensure_ascii=False, indent=2)
    prompt_json = json.dumps(summarize_requirement(prompt), ensure_ascii=False)
    return f"""// Generated by Atoms Agent Demo API
export default function {component_name}() {{
  const mode = "{mode}";
  const requirement = {prompt_json};
  const cards = {cards_json};

  return (
    <AppShell mode={{mode}}>
      <Hero title="{template["title"]}" description={{requirement}} />
      <FeatureGrid cards={{cards}} />
      <AgentRuntime preview code logs export publish />
    </AppShell>
  );
}}
"""


def make_build(prompt: str, template_id: TemplateId, mode: BuildMode, source: str = "chat") -> dict:
    resolved_template_id = detect_template(prompt, template_id)
    template = TEMPLATES[resolved_template_id]
    build_id = f"build_{uuid.uuid4().hex[:10]}"
    requirement = summarize_requirement(prompt)
    created = now_iso()
    steps = [
        {
            "id": "planner",
            "agent": "Planner",
            "title": "提取产品范围、页面结构和数据模型",
            "durationMs": 700 if mode == "fast" else 1100,
        },
        {
            "id": "coder",
            "agent": "Coder",
            "title": "生成组件、状态、示例数据和交互事件",
            "durationMs": 900 if mode == "fast" else 1400,
        },
        {
            "id": "verifier",
            "agent": "Verifier",
            "title": "检查响应式布局、空状态、日志和发布流程",
            "durationMs": 650 if mode == "fast" else 1200,
        },
    ]
    preview = {
        "name": template["name"],
        "slug": template["slug"],
        "title": template["title"],
        "copy": f"基于你的需求：{requirement}" if prompt else template["copy"],
        "buttons": template["buttons"],
        "cards": template["cards"],
        "url": f"https://preview.atoms.local/{template['slug']}",
    }
    logs = [
        f"[{created}] [{source}] prompt received",
        f"[planner] selected template={resolved_template_id}, mode={mode}",
        "[coder] generated route, components, state model, preview data",
        "[verifier] responsive pass, contrast pass, empty-state pass",
        f"[artifact] build_id={build_id}",
    ]
    build = {
        "id": build_id,
        "status": "ready",
        "mode": mode,
        "templateId": resolved_template_id,
        "prompt": prompt,
        "createdAt": created,
        "steps": steps,
        "message": "预览已经更新。你可以继续要求我添加页面、改样式、补数据库字段，或直接发布。",
        "preview": preview,
        "code": generated_code(template, prompt or template["copy"], mode),
        "logs": logs,
    }
    BUILDS[build_id] = build
    return build


app = FastAPI(title="Atoms Agent Builder Demo API", version="1.0.0")

frontend_origin = os.getenv("FRONTEND_ORIGIN", "*")
allow_origins = ["*"] if frontend_origin == "*" else [origin.strip() for origin in frontend_origin.split(",")]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root() -> dict:
    return {"name": "Atoms Agent Builder Demo API", "status": "ok", "docs": "/docs"}


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "time": now_iso()}


@app.get("/api/templates")
def list_templates() -> dict:
    return {"templates": list(TEMPLATES.values())}


@app.get("/api/projects")
def list_projects() -> dict:
    return {"projects": PROJECTS}


@app.post("/api/builds")
def create_build(request: BuildRequest) -> dict:
    build = make_build(request.prompt, request.template_id, request.mode)
    return {"build": build}


@app.post("/api/builds/rerun")
def rerun_build(request: RerunRequest) -> dict:
    previous = BUILDS.get(request.build_id)
    if not previous:
        raise HTTPException(status_code=404, detail="Build not found")
    prompt = request.instruction or f"重新运行 {previous['preview']['name']}，保持当前功能但优化视觉层级。"
    build = make_build(prompt, previous["templateId"], request.mode, source="rerun")
    return {"build": build}


@app.get("/api/builds/{build_id}")
def get_build(build_id: str) -> dict:
    build = BUILDS.get(build_id)
    if not build:
        raise HTTPException(status_code=404, detail="Build not found")
    return {"build": build}


@app.get("/api/builds/{build_id}/export")
def export_build(build_id: str):
    build = BUILDS.get(build_id)
    if not build:
        raise HTTPException(status_code=404, detail="Build not found")

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("README.md", f"# {build['preview']['name']}\n\nGenerated by Atoms Agent Demo API.\n")
        archive.writestr("src/App.jsx", build["code"])
        archive.writestr("build.json", json.dumps(build, ensure_ascii=False, indent=2))
        archive.writestr("logs.txt", "\n".join(build["logs"]))
    buffer.seek(0)

    filename = f"{build['preview']['slug']}-{int(time.time())}.zip"
    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    return StreamingResponse(buffer, media_type="application/zip", headers=headers)


@app.post("/api/publish")
def publish_build(request: PublishRequest) -> dict:
    build = BUILDS.get(request.build_id)
    if not build:
        raise HTTPException(status_code=404, detail="Build not found")
    published = {
        "buildId": build["id"],
        "status": "published",
        "publishedAt": now_iso(),
        "url": f"https://preview.atoms.local/live/{build['preview']['slug']}",
    }
    PUBLISHED[build["id"]] = published
    return {"publish": published}
