from __future__ import annotations

import io
import json
import os
import re
import time
import uuid
import zipfile
from datetime import datetime, timezone
from typing import Literal

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field


TemplateId = Literal["crm", "shop", "learn"]
BuildMode = Literal["fast", "deep"]


class BuildRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=1200)
    template_id: TemplateId = "crm"
    mode: BuildMode = "fast"
    history: list[dict[str, str]] = Field(default_factory=list)


class RerunRequest(BaseModel):
    build_id: str
    instruction: str | None = None
    mode: BuildMode = "fast"


class PublishRequest(BaseModel):
    build_id: str


TEMPLATES = {
    "crm": {
        "id": "crm",
        "name": "AI CRM Sprint",
        "slug": "ai-crm-sprint",
        "summary": "Pipeline, tasks, analytics, permissions, and follow-up workflows.",
        "title": "Sales pipeline that updates itself",
        "copy": "智能体已经生成客户列表、销售阶段、提醒任务和转化分析。继续对话即可增删页面或调整数据模型。",
        "buttons": ["Create lead", "Review pipeline"],
        "cards": [
            {"title": "Pipeline", "copy": "按阶段管理机会，自动标记高优先级客户。"},
            {"title": "Tasks", "copy": "从邮件和会议纪要中提取下一步行动。"},
            {"title": "Analytics", "copy": "追踪赢单率、响应时间和预测收入。"},
        ],
    },
    "shop": {
        "id": "shop",
        "name": "Commerce Launchpad",
        "slug": "commerce-launchpad",
        "summary": "Catalog, cart, checkout, order operations, and inventory states.",
        "title": "Storefront, checkout, and ops in one build",
        "copy": "生成商品目录、库存状态、购物车、结账流程和订单后台，适合快速验证电商项目。",
        "buttons": ["Add product", "Open orders"],
        "cards": [
            {"title": "Catalog", "copy": "支持分类、标签、变体和库存状态。"},
            {"title": "Checkout", "copy": "包含地址、优惠码、支付摘要和确认页。"},
            {"title": "Orders", "copy": "按状态追踪履约、退款和客户沟通。"},
        ],
    },
    "learn": {
        "id": "learn",
        "name": "Learning Studio",
        "slug": "learning-studio",
        "summary": "Courses, lessons, quizzes, learner progress, and authoring tools.",
        "title": "Course platform with progress-aware lessons",
        "copy": "生成课程首页、课时播放器、测验、学习进度和教师内容管理工作台。",
        "buttons": ["Create course", "Preview lesson"],
        "cards": [
            {"title": "Courses", "copy": "按模块组织视频、阅读材料和附件。"},
            {"title": "Quizzes", "copy": "自动生成题目、反馈和通过规则。"},
            {"title": "Progress", "copy": "展示完成率、薄弱知识点和学习提醒。"},
        ],
    },
}


PROJECTS = [
    {"id": "crm-sprint", "name": "AI CRM Sprint", "templateId": "crm", "updated": "Now"},
    {"id": "finops-board", "name": "FinOps Board", "templateId": "shop", "updated": "2h"},
    {"id": "docs-portal", "name": "Docs Portal", "templateId": "learn", "updated": "1d"},
]


BUILDS: dict[str, dict] = {}
PUBLISHED: dict[str, dict] = {}

AI_API_BASE_URL = os.getenv("AI_API_BASE_URL", "").rstrip("/")
AI_API_KEY = os.getenv("AI_API_KEY", "")
AI_MODEL = os.getenv("AI_MODEL", "gpt-4o-mini")
AI_TIMEOUT_SECONDS = float(os.getenv("AI_TIMEOUT_SECONDS", "40"))
AI_STATUS = {
    "enabled": bool(AI_API_BASE_URL and AI_API_KEY),
    "last_ok": False,
    "last_error": "",
}


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def detect_template(prompt: str, fallback: TemplateId) -> TemplateId:
    text = prompt.lower()
    if any(word in text for word in ["电商", "商品", "订单", "购物", "shop", "commerce", "store"]):
        return "shop"
    if any(word in text for word in ["课程", "学习", "lesson", "course", "education", "quiz"]):
        return "learn"
    if any(word in text for word in ["crm", "销售", "客户", "pipeline", "lead"]):
        return "crm"
    return fallback


def summarize_requirement(prompt: str) -> str:
    prompt = " ".join(prompt.strip().split())
    if len(prompt) <= 92:
        return prompt
    return f"{prompt[:92]}..."


def generated_code(template: dict, prompt: str, mode: BuildMode) -> str:
    component_name = "".join(part for part in template["name"].title() if part.isalnum())
    cards_json = json.dumps(template["cards"], ensure_ascii=False, indent=2)
    prompt_json = json.dumps(summarize_requirement(prompt), ensure_ascii=False)
    return f"""// Generated by Atoms Agent Demo API
export default function {component_name}() {{
  const mode = "{mode}";
  const requirement = {prompt_json};
  const cards = {cards_json};

  return (
    <AppShell mode={{mode}}>
      <Hero title="{template["title"]}" description={{requirement}} />
      <FeatureGrid cards={{cards}} />
      <AgentRuntime preview code logs export publish />
    </AppShell>
  );
}}
"""


def generated_files(build_id: str, template: dict, preview: dict, code: str, prompt: str, mode: BuildMode) -> list[dict]:
    package_json = {
        "scripts": {"dev": "vite", "build": "vite build", "preview": "vite preview"},
        "dependencies": {
            "@vitejs/plugin-react": "latest",
            "vite": "latest",
            "react": "latest",
            "react-dom": "latest",
        },
        "devDependencies": {},
    }
    build_json = {
        "buildId": build_id,
        "mode": mode,
        "template": template["id"],
        "preview": preview,
    }
    readme = f"""# {preview["name"]}

Generated by Atoms Agent Builder Demo.

## Requirement

{prompt}

## Preview

- Title: {preview["title"]}
- URL: {preview["url"]}

## File Structure

- `frontend/src/App.jsx` - generated React app
- `frontend/src/styles.css` - generated styles
- `frontend/package.json` - frontend dependencies and scripts
- `build.json` - structured build metadata
"""
    styles = f""":root {{
  font-family: Inter, system-ui, sans-serif;
  color: #172033;
  background: #f7f7f4;
}}

.app {{
  min-height: 100vh;
  padding: 32px;
}}

.hero {{
  border-radius: 16px;
  padding: 32px;
  background: {"#111827" if preview.get("theme") == "dark" else "#ffffff"};
  color: {"#f8fafc" if preview.get("theme") == "dark" else "#172033"};
}}
"""
    index_html = """<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/App.jsx"></script>
  </body>
</html>
"""
    return [
        {"path": "README.md", "type": "md", "content": readme},
        {"path": "build.json", "type": "json", "content": json.dumps(build_json, ensure_ascii=False, indent=2)},
        {"path": "frontend/package.json", "type": "json", "content": json.dumps(package_json, ensure_ascii=False, indent=2)},
        {"path": "frontend/index.html", "type": "html", "content": index_html},
        {"path": "frontend/src/App.jsx", "type": "jsx", "content": code},
        {"path": "frontend/src/styles.css", "type": "css", "content": styles},
    ]


def extract_json_object(text: str) -> dict | None:
    """Parse strict JSON first, then recover JSON wrapped in markdown fences."""
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.DOTALL)
    if fenced:
        try:
            return json.loads(fenced.group(1))
        except json.JSONDecodeError:
            return None

    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            return None
    return None


def normalize_cards(value: object, fallback_cards: list[dict]) -> list[dict]:
    if not isinstance(value, list):
        return fallback_cards
    cards = []
    for item in value[:6]:
        if not isinstance(item, dict):
            continue
        title = str(item.get("title", "")).strip()
        copy = str(item.get("copy", "")).strip()
        if title and copy:
            cards.append({"title": title[:48], "copy": copy[:160]})
    return cards or fallback_cards


def normalize_buttons(value: object, fallback_buttons: list[str]) -> list[str]:
    if not isinstance(value, list):
        return fallback_buttons
    buttons = [str(item).strip()[:32] for item in value[:3] if str(item).strip()]
    return buttons or fallback_buttons


def normalize_list(value: object, fallback: list[str], limit: int = 6, item_limit: int = 48) -> list[str]:
    if not isinstance(value, list):
        return fallback
    items = [str(item).strip()[:item_limit] for item in value[:limit] if str(item).strip()]
    return items or fallback


def normalize_sections(value: object) -> list[dict]:
    if not isinstance(value, list):
        return []
    sections = []
    for item in value[:5]:
        if not isinstance(item, dict):
            continue
        title = str(item.get("title", "")).strip()
        copy = str(item.get("copy", "")).strip()
        bullets = normalize_list(item.get("bullets"), [], limit=4, item_limit=80)
        if title and copy:
            sections.append({"title": title[:56], "copy": copy[:220], "bullets": bullets})
    return sections


def apply_ai_result(build: dict, ai_result: dict | None, fallback_template: dict) -> dict:
    build["ai"] = {
        "enabled": AI_STATUS["enabled"],
        "used": bool(ai_result),
        "model": AI_MODEL if AI_STATUS["enabled"] else "",
        "lastError": AI_STATUS["last_error"],
    }
    if not ai_result:
        reason = AI_STATUS["last_error"] or "AI_API_BASE_URL or AI_API_KEY is not configured"
        build["logs"].append(f"[ai] provider unavailable; used deterministic fallback; reason={reason}")
        return build

    preview = ai_result.get("preview") if isinstance(ai_result.get("preview"), dict) else {}
    message = str(ai_result.get("message", "")).strip()
    code = str(ai_result.get("code", "")).strip()
    logs = ai_result.get("logs") if isinstance(ai_result.get("logs"), list) else []

    build["message"] = message[:500] or build["message"]
    build["preview"]["title"] = str(preview.get("title", build["preview"]["title"])).strip()[:96]
    build["preview"]["copy"] = str(preview.get("copy", build["preview"]["copy"])).strip()[:360]
    build["preview"]["buttons"] = normalize_buttons(preview.get("buttons"), fallback_template["buttons"])
    build["preview"]["cards"] = normalize_cards(preview.get("cards"), fallback_template["cards"])
    build["preview"]["theme"] = str(preview.get("theme", "light")).strip()[:24] or "light"
    build["preview"]["nav"] = normalize_list(preview.get("nav"), ["Home", "Dashboard", "Settings"], limit=5)
    build["preview"]["metrics"] = normalize_cards(preview.get("metrics"), [])
    build["preview"]["sections"] = normalize_sections(preview.get("sections"))
    if code:
        build["code"] = code[:9000]

    clean_logs = [str(item).strip()[:240] for item in logs if str(item).strip()]
    build["logs"].extend([f"[ai] {item}" for item in clean_logs[:8]])
    build["logs"].append("[ai] model response applied to preview and code")
    return build


def chat_completions_endpoint() -> str:
    if AI_API_BASE_URL.endswith("/chat/completions"):
        return AI_API_BASE_URL
    return f"{AI_API_BASE_URL}/chat/completions"


def ai_system_prompt() -> str:
    return """
You are the backend agent runtime for an Atoms-style app builder.
The user describes an app. Generate a realistic interactive app preview and React code.

Return only valid JSON with this exact shape:
{
  "message": "short Chinese assistant response",
  "preview": {
    "title": "preview hero title",
    "copy": "Chinese summary based on the user request",
    "theme": "light | dark | minimal | playful | enterprise",
    "nav": ["nav item"],
    "buttons": ["primary action", "secondary action"],
    "metrics": [
      {"title": "metric label", "copy": "metric value or short status"}
    ],
    "cards": [
      {"title": "feature name", "copy": "short Chinese feature description"}
    ],
    "sections": [
      {"title": "page section", "copy": "what this section contains", "bullets": ["detail"]}
    ]
  },
  "code": "React JSX code string for the generated app",
  "logs": ["planner log", "coder log", "verifier log"]
}

Rules:
- Keep the generated app concrete and useful.
- Make the preview visibly different for different user requests, not just rewritten text.
- Use nav, metrics, cards, and sections to describe the generated page structure.
- Do not include markdown fences.
- The code should be displayable as source in a demo. It does not need external packages.
- Include Planner, Coder, and Verifier behavior in logs.
""".strip()


async def call_ai_provider(prompt: str, template: dict, mode: BuildMode, history: list[dict[str, str]]) -> dict | None:
    if not AI_API_BASE_URL or not AI_API_KEY:
        AI_STATUS["enabled"] = False
        AI_STATUS["last_ok"] = False
        AI_STATUS["last_error"] = "AI_API_BASE_URL or AI_API_KEY is missing"
        return None

    AI_STATUS["enabled"] = True
    AI_STATUS["last_error"] = ""
    endpoint = chat_completions_endpoint()
    compact_history = [
        {"role": item.get("role", "user"), "content": item.get("content", "")[:800]}
        for item in history[-8:]
        if item.get("content")
    ]
    user_payload = {
        "prompt": prompt,
        "mode": mode,
        "starterTemplate": {
            "name": template["name"],
            "summary": template["summary"],
            "currentCards": template["cards"],
        },
    }

    body = {
        "model": AI_MODEL,
        "temperature": 0.45 if mode == "fast" else 0.7,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": ai_system_prompt()},
            *compact_history,
            {"role": "user", "content": json.dumps(user_payload, ensure_ascii=False)},
        ],
    }

    try:
        async with httpx.AsyncClient(timeout=AI_TIMEOUT_SECONDS) as client:
            response = await client.post(
                endpoint,
                headers={"Authorization": f"Bearer {AI_API_KEY}", "Content-Type": "application/json"},
                json=body,
            )
            response.raise_for_status()
            payload = response.json()
    except httpx.HTTPStatusError as exc:
        detail = exc.response.text[:500] if exc.response is not None else ""
        AI_STATUS["last_ok"] = False
        AI_STATUS["last_error"] = f"HTTP {exc.response.status_code if exc.response else 'unknown'} from AI provider: {detail}"
        return None
    except Exception as exc:
        AI_STATUS["last_ok"] = False
        AI_STATUS["last_error"] = f"{type(exc).__name__}: {str(exc)[:500]}"
        return None

    content = (
        payload.get("choices", [{}])[0]
        .get("message", {})
        .get("content", "")
    )
    if not content:
        AI_STATUS["last_ok"] = False
        AI_STATUS["last_error"] = "AI provider returned an empty message"
        return None
    parsed = extract_json_object(content)
    if not parsed:
        AI_STATUS["last_ok"] = False
        AI_STATUS["last_error"] = "AI provider response was not valid JSON"
        return None
    AI_STATUS["last_ok"] = True
    AI_STATUS["last_error"] = ""
    return parsed


async def make_build(
    prompt: str,
    template_id: TemplateId,
    mode: BuildMode,
    source: str = "chat",
    history: list[dict[str, str]] | None = None,
) -> dict:
    resolved_template_id = detect_template(prompt, template_id)
    template = TEMPLATES[resolved_template_id]
    build_id = f"build_{uuid.uuid4().hex[:10]}"
    requirement = summarize_requirement(prompt)
    created = now_iso()
    steps = [
        {
            "id": "planner",
            "agent": "Planner",
            "title": "提取产品范围、页面结构和数据模型",
            "durationMs": 700 if mode == "fast" else 1100,
        },
        {
            "id": "coder",
            "agent": "Coder",
            "title": "生成组件、状态、示例数据和交互事件",
            "durationMs": 900 if mode == "fast" else 1400,
        },
        {
            "id": "verifier",
            "agent": "Verifier",
            "title": "检查响应式布局、空状态、日志和发布流程",
            "durationMs": 650 if mode == "fast" else 1200,
        },
    ]
    preview = {
        "name": template["name"],
        "slug": template["slug"],
        "title": template["title"],
        "copy": f"基于你的需求：{requirement}" if prompt else template["copy"],
        "buttons": template["buttons"],
        "cards": template["cards"],
        "url": f"https://preview.atoms.local/{template['slug']}",
    }
    logs = [
        f"[{created}] [{source}] prompt received",
        f"[planner] selected template={resolved_template_id}, mode={mode}",
        "[coder] generated route, components, state model, preview data",
        "[verifier] responsive pass, contrast pass, empty-state pass",
        f"[artifact] build_id={build_id}",
    ]
    build = {
        "id": build_id,
        "status": "ready",
        "mode": mode,
        "templateId": resolved_template_id,
        "prompt": prompt,
        "createdAt": created,
        "steps": steps,
        "message": "预览已经更新。你可以继续要求我添加页面、改样式、补数据库字段，或直接发布。",
        "preview": preview,
        "code": generated_code(template, prompt or template["copy"], mode),
        "files": [],
        "logs": logs,
    }
    ai_result = await call_ai_provider(prompt, template, mode, history or [])
    build = apply_ai_result(build, ai_result, template)
    build["files"] = generated_files(build_id, template, build["preview"], build["code"], prompt or template["copy"], mode)
    BUILDS[build_id] = build
    return build


app = FastAPI(title="Atoms Agent Builder Demo API", version="1.0.0")

frontend_origin = os.getenv("FRONTEND_ORIGIN", "*")
allow_origins = ["*"] if frontend_origin == "*" else [origin.strip() for origin in frontend_origin.split(",")]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root() -> dict:
    return {"name": "Atoms Agent Builder Demo API", "status": "ok", "docs": "/docs"}


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "time": now_iso()}


@app.get("/api/ai/status")
def ai_status() -> dict:
    return {
        "enabled": bool(AI_API_BASE_URL and AI_API_KEY),
        "baseUrl": AI_API_BASE_URL,
        "endpoint": chat_completions_endpoint() if AI_API_BASE_URL else "",
        "model": AI_MODEL,
        "hasKey": bool(AI_API_KEY),
        "lastOk": AI_STATUS["last_ok"],
        "lastError": AI_STATUS["last_error"],
    }


@app.get("/api/templates")
def list_templates() -> dict:
    return {"templates": list(TEMPLATES.values())}


@app.get("/api/projects")
def list_projects() -> dict:
    return {"projects": PROJECTS}


@app.post("/api/builds")
async def create_build(request: BuildRequest) -> dict:
    build = await make_build(request.prompt, request.template_id, request.mode, history=request.history)
    return {"build": build}


@app.post("/api/builds/rerun")
async def rerun_build(request: RerunRequest) -> dict:
    previous = BUILDS.get(request.build_id)
    if not previous:
        raise HTTPException(status_code=404, detail="Build not found")
    prompt = request.instruction or f"重新运行 {previous['preview']['name']}，保持当前功能但优化视觉层级。"
    build = await make_build(prompt, previous["templateId"], request.mode, source="rerun")
    return {"build": build}


@app.get("/api/builds/{build_id}")
def get_build(build_id: str) -> dict:
    build = BUILDS.get(build_id)
    if not build:
        raise HTTPException(status_code=404, detail="Build not found")
    return {"build": build}


@app.get("/api/builds/{build_id}/export")
def export_build(build_id: str):
    build = BUILDS.get(build_id)
    if not build:
        raise HTTPException(status_code=404, detail="Build not found")

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        if build.get("files"):
            for file in build["files"]:
                archive.writestr(file["path"], file["content"])
        else:
            archive.writestr("README.md", f"# {build['preview']['name']}\n\nGenerated by Atoms Agent Demo API.\n")
            archive.writestr("frontend/src/App.jsx", build["code"])
            archive.writestr("build.json", json.dumps(build, ensure_ascii=False, indent=2))
        archive.writestr("logs.txt", "\n".join(build["logs"]))
    buffer.seek(0)

    filename = f"{build['preview']['slug']}-{int(time.time())}.zip"
    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    return StreamingResponse(buffer, media_type="application/zip", headers=headers)


@app.post("/api/publish")
def publish_build(request: PublishRequest) -> dict:
    build = BUILDS.get(request.build_id)
    if not build:
        raise HTTPException(status_code=404, detail="Build not found")
    published = {
        "buildId": build["id"],
        "status": "published",
        "publishedAt": now_iso(),
        "url": f"https://preview.atoms.local/live/{build['preview']['slug']}",
    }
    PUBLISHED[build["id"]] = published
    return {"publish": published}
